### ISSUE TITLE
Not connecting to GoTo Webinar

### ISSUE THREAD

**Issue by KilakwaBT** [veda-consulting-company/uk.co.vedaconsulting.gotowebinar#46]
We have had an event setup and running fine until last Friday (June 19, 2020).  Now we are getting a registration error in Civi. We seem to have lost our connection to GoTo Webinar. When I look at the settings page the user and password are missing. I enter the correct information but it will not connect. I also tried setting up a new app in for GoToWebinar with new keys and still no luck. I see the following in the CiviCRM log:

` [info] Deprecated: Group='Webinar Preferences'. Name='access_token'. Defaults should come from metadata`

We were running CiviCRM ver 5.24.4. on WordPress. We upgraded to 5.26.2 still no luck. We also have another site connected th the GoToWebinar account and are experiencing the same issue.

**Comment by KilakwaBT** [comment]
After doing some more research I found that our connections were disabled after this maintenance on June 20

https://status-goto-developer.logmeininc.com/incidents/t96n7rm8ypr7

Haven't been able to connect since with existing or new accounts on various sites. Get the same error as above. Any thoughts? I reached out to GotoWebinar developer support but haven't heard back.

**Comment by veda-consulting** [comment]
HI @KilakwaBT I'm afraid not, we simply maintain the extension for clients and haven't got any first hand experience of setting up a new gotowebinar paid account.

Please do keep up informed.

**Comment by paulrooney** [comment]
Looks like this is a related issue:
https://github.com/veda-consulting-company/uk.co.vedaconsulting.mailchimp/issues/276

**Comment by rajeshrhino** [comment]
Resolved in PR #52
